import dessinMSDA
import turtle

def dessin_avion():
    '''C'est un module qui importe le module dessinMSDA et qui permet de dessiner un avion.'''
    turtle.color('blue')
    turtle.up()
    turtle.goto(100,100)
    turtle.left(45)
    turtle.down()
    dessinMSDA.dessin_demi_cercle(15,'blue')
    turtle.forward(90)
    turtle.right(60)
    turtle.forward(110)
    turtle.left(60)
    turtle.forward(15)
    turtle.left(105)
    turtle.forward(100)
    turtle.right(100)
    turtle.forward(60)
    turtle.right(60)
    turtle.forward(40)
    turtle.left(60)
    turtle.forward(15)
    turtle.left(105)
    turtle.forward(50)
    turtle.right(60)
    turtle.forward(40)
    turtle.left(60)
    turtle.forward(15)
    turtle.left(105)
    turtle.forward(50)
    turtle.right(30)
    turtle.forward(60)
    turtle.right(90)
    turtle.forward(100)
    turtle.left(60)
    turtle.forward(15)
    turtle.left(100)
    turtle.forward(110)
    turtle.right(73)
    turtle.forward(90)
    turtle.hideturtle()