import turtle
import dessinMSDA
def dessin_maison():
    '''Importe le module dessinMSDA et permet de dessiner une maison'''
    turtle.title("dessin d'une maison")
    turtle.up()
    turtle.goto(-150,-120)
    turtle.down()
    turtle.begin_fill()
    dessinMSDA.dessin_rectangle(130,150,'yellow')
    turtle.end_fill()
    turtle.up()
    turtle.goto(-120,-120)
    turtle.begin_fill()
    dessinMSDA.dessin_rectangle(40,75,'saddlebrown')
    turtle.end_fill()
    turtle.up()
    turtle.goto(-60,-70)
    turtle.begin_fill()
    dessinMSDA.dessin_carre(10,'white')
    turtle.end_fill()
    turtle.begin_fill()
    turtle.up()
    turtle.goto(-50,-70)
    dessinMSDA.dessin_carre(10,'white')
    turtle.end_fill()
    turtle.begin_fill()
    turtle.up()
    turtle.goto(-60,-60)
    dessinMSDA.dessin_carre(10,'white')
    turtle.end_fill()
    turtle.begin_fill()
    turtle.up()
    turtle.goto(-50,-60)
    dessinMSDA.dessin_carre(10,'white')
    turtle.end_fill()
    turtle.up()
    turtle.goto(-160,30)
    turtle.down()
    turtle.begin_fill()
    dessinMSDA.dessin_triangle_rectangle(150,'saddlebrown')
    turtle.end_fill()
    turtle.begin_fill()
    turtle.up()
    turtle.goto(-50,55)
    dessinMSDA.dessin_rectangle(15,45,'white')
    turtle.end_fill()
    turtle.begin_fill()
    turtle.up()
    turtle.goto(-150,-120)
    dessinMSDA.dessin_rectangle(130,10,'black')
    turtle.end_fill()
    turtle.begin_fill()
    turtle.up()
    turtle.goto(-125,-120)
    dessinMSDA.dessin_rectangle(50,10,'white')
    turtle.end_fill()